?version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ABS_MIN_STARS=${ABS_MIN_STARS:-0}
      - ABS_MAX_STARS=${ABS_MAX_STARS:-1000000}
      - DEFAULT_CHUNK_SIZE=${DEFAULT_CHUNK_SIZE:-100}
    command: ["uvicorn", "untestables.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scanner:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ABS_MIN_STARS=${ABS_MIN_STARS:-0}
      - ABS_MAX_STARS=${ABS_MAX_STARS:-1000000}
      - DEFAULT_CHUNK_SIZE=${DEFAULT_CHUNK_SIZE:-100}
    command: ["poetry", "run", "untestables", "find-repos"]

  analyzer:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ABS_MIN_STARS=${ABS_MIN_STARS:-0}
      - ABS_MAX_STARS=${ABS_MAX_STARS:-1000000}
      - DEFAULT_CHUNK_SIZE=${DEFAULT_CHUNK_SIZE:-100}
      - SCANNER_COMMAND=${SCANNER_COMMAND:-poetry run untestables find-repos}
    command: ["poetry", "run", "untestables", "scan"]
